import React from "react";
import { CUADRANTES } from "../cuadrante/constantes";

interface Jugador { matricula:string; pista:string|null; haDadoPista:boolean; haVotado:boolean; votos?:number; }
interface Sala { codigo:string; estado:"espera"|"pistas"|"votacion"|"finalizada"|"abandonada"; anfitrion:string; soyAnfitrion:boolean; ronda:number; rol:"infiltrado"|"equipo"|null; palabra:string|null; tematica:string|null; jugadores:Jugador[]; miPista:string|null; miVoto:string|null; infiltrado:string|null; acusado:string|null; empate:boolean; pases:number; }
interface Pendiente { codigo:string; anfitrion:string; }
const operadores=Array.from(new Map(CUADRANTES.flatMap(c=>c.operadores).map(o=>[o.matricula,o])).values()).sort((a,b)=>a.matricula.localeCompare(b.matricula));
const nombre=(m:string)=>operadores.find(o=>o.matricula===m)?.nombre??"Operador CRA";

export const JuegoInfiltrado:React.FC=()=>{
  const [matricula,setMatricula]=React.useState(()=>localStorage.getItem("cra-zona-descanso-matricula")??"RMI");
  const [codigo,setCodigo]=React.useState(()=>localStorage.getItem("cra-infiltrado-sala")??"");
  const [entrada,setEntrada]=React.useState(""); const [sala,setSala]=React.useState<Sala|null>(null);
  const [pendientes,setPendientes]=React.useState<Pendiente[]>([]); const [pista,setPista]=React.useState("");
  const [voto,setVoto]=React.useState(""); const [mensaje,setMensaje]=React.useState("Crea una sala o únete con un código."); const [cargando,setCargando]=React.useState(false);
  const peticion=async(cuerpo:Record<string,unknown>)=>{const r=await fetch("/api/infiltrado",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({...cuerpo,matricula})});const d=await r.json() as {sala?:Sala;codigo?:string;error?:string;abandonada?:boolean};if(!r.ok)throw new Error(d.error||"No se pudo completar la acción.");return d;};
  const cargarLobby=React.useCallback(async()=>{const r=await fetch("/api/infiltrado",{credentials:"same-origin",cache:"no-store"});if(r.ok){const d=await r.json() as {pendientes?:Pendiente[]};setPendientes(d.pendientes??[]);}},[]);
  const cargarSala=React.useCallback(async(c:string)=>{if(!c)return;const r=await fetch(`/api/infiltrado?codigo=${encodeURIComponent(c)}&matricula=${encodeURIComponent(matricula)}`,{credentials:"same-origin",cache:"no-store"});const d=await r.json() as {sala?:Sala;error?:string};if(r.ok&&d.sala)setSala(d.sala);},[matricula]);
  React.useEffect(()=>{localStorage.setItem("cra-zona-descanso-matricula",matricula);},[matricula]);
  React.useEffect(()=>{cargarLobby().catch(()=>undefined);if(codigo)cargarSala(codigo).catch(()=>undefined);},[cargarLobby,cargarSala,codigo]);
  React.useEffect(()=>{if(!codigo||!sala||sala.estado==="abandonada")return;const i=window.setInterval(()=>cargarSala(codigo).catch(()=>undefined),1500);return()=>window.clearInterval(i);},[codigo,sala?.estado,cargarSala]);
  const ejecutar=async(cuerpo:Record<string,unknown>,texto?:string)=>{setCargando(true);try{const d=await peticion(cuerpo);if(d.codigo){setCodigo(d.codigo);localStorage.setItem("cra-infiltrado-sala",d.codigo);await cargarSala(d.codigo);}if(d.sala){setSala(d.sala);setCodigo(d.sala.codigo);localStorage.setItem("cra-infiltrado-sala",d.sala.codigo);}if(texto)setMensaje(texto);}catch(e){setMensaje(e instanceof Error?e.message:"No se pudo completar.");}finally{setCargando(false);}};
  const salir=async()=>{try{if(codigo)await peticion({accion:"abandonar",codigo});}catch{/* salida local */}setSala(null);setCodigo("");localStorage.removeItem("cra-infiltrado-sala");cargarLobby().catch(()=>undefined);};

  if(!sala)return <section className="infiltrado-lobby">
    <header><span>Multijugador · 3 a 10 operadores</span><h2>El infiltrado</h2><p>Todos conocen la palabra menos uno. Da una pista, observa y vota.</p></header>
    <label>Jugador<select value={matricula} onChange={e=>setMatricula(e.target.value)}>{operadores.map(o=><option value={o.matricula} key={o.matricula}>{o.matricula} · {o.nombre}</option>)}</select></label>
    <button className="infiltrado-principal" type="button" disabled={cargando} onClick={()=>ejecutar({accion:"crear"},"Sala creada. Comparte el código.")}>Crear sala</button>
    <div className="infiltrado-unirse"><input value={entrada} maxLength={8} placeholder="INF-7K4P" onChange={e=>setEntrada(e.target.value.toUpperCase())}/><button type="button" disabled={!entrada||cargando} onClick={()=>ejecutar({accion:"unirse",codigo:entrada},"Te has unido a la sala.")}>Unirme</button></div>
    <p className="codigo-secreto-mensaje">{mensaje}</p>
    <div className="infiltrado-pendientes"><h3>Salas abiertas</h3>{pendientes.length?pendientes.map(p=><button type="button" key={p.codigo} onClick={()=>ejecutar({accion:"unirse",codigo:`INF-${p.codigo}`})}><b>INF-{p.codigo}</b><span>{p.anfitrion} · {nombre(p.anfitrion)}</span><strong>Entrar</strong></button>):<p>No hay salas esperando jugadores.</p>}</div>
  </section>;

  const pistasDadas=sala.jugadores.filter(j=>j.haDadoPista).length; const votosDados=sala.jugadores.filter(j=>j.haVotado).length;
  return <section className="infiltrado-juego">
    <header><div><span>{sala.codigo} · Ronda {sala.ronda}</span><h2>El infiltrado</h2></div><button type="button" onClick={salir}>Salir</button></header>
    {sala.estado==="espera"&&<div className="infiltrado-espera"><span>CÓDIGO DE SALA</span><h3>{sala.codigo}</h3><p>Comparte el código. Se necesitan al menos 3 jugadores.</p><div className="infiltrado-jugadores">{sala.jugadores.map(j=><article key={j.matricula}><i>{j.matricula.slice(0,2)}</i><strong>{j.matricula}</strong><small>{nombre(j.matricula)}</small>{j.matricula===sala.anfitrion&&<b>Anfitrión</b>}</article>)}</div>{sala.soyAnfitrion?<button className="infiltrado-principal" type="button" disabled={sala.jugadores.length<3||cargando} onClick={()=>ejecutar({accion:"iniciar",codigo:sala.codigo})}>Iniciar con {sala.jugadores.length} jugadores</button>:<p>Esperando a que el anfitrión inicie…</p>}</div>}
    {sala.estado==="pistas"&&<><div className="infiltrado-tematica"><small>Temática · Ronda {sala.ronda}</small><strong>{sala.tematica}</strong></div><div className={`infiltrado-rol ${sala.rol}`}><span>{sala.rol==="infiltrado"?"⚠":"✓"}</span><div><small>Tu papel secreto</small><h3>{sala.rol==="infiltrado"?"ERES EL INFILTRADO":sala.palabra}</h3><p>{sala.rol==="infiltrado"?"Conoces la temática, pero no la palabra. Disimula con una pista creíble.":"Escribe una única palabra relacionada, sin usar la palabra secreta."}</p></div></div><div className="infiltrado-progreso"><span style={{width:`${pistasDadas/sala.jugadores.length*100}%`}}/><p>{pistasDadas} de {sala.jugadores.length} pistas enviadas</p></div>{!sala.miPista?<div className="infiltrado-pista"><input value={pista} maxLength={20} placeholder="Una sola palabra…" onChange={e=>setPista(e.target.value.replace(/[^\p{L}]/gu,""))}/><button type="button" disabled={pista.trim().length<2||cargando} onClick={()=>ejecutar({accion:"pista",codigo:sala.codigo,pista},"Pista enviada.")}>Enviar pista</button></div>:<div className="infiltrado-enviado">✓ Tu pista: <strong>{sala.miPista}</strong><small>Esperando las demás pistas…</small></div>}</>}
    {sala.estado==="votacion"&&<div className="infiltrado-votacion"><header><span>{sala.tematica} · Ronda {sala.ronda}</span><h3>¿Quién es el infiltrado?</h3><p>Solo será descubierto con mayoría absoluta. Si no la consigue, habrá otra palabra.</p></header><div className="infiltrado-votos-progreso"><span style={{width:`${votosDados/sala.jugadores.length*100}%`}}/><b>{votosDados}/{sala.jugadores.length} votos</b></div><div className="infiltrado-candidatos">{sala.jugadores.map((j,i)=><button type="button" disabled={j.matricula===matricula||Boolean(sala.miVoto)||cargando} className={`${voto===j.matricula?"seleccionado":""} ${sala.miVoto===j.matricula?"votado":""}`} onClick={()=>setVoto(j.matricula)} key={j.matricula}><span className={`avatar color-${i%5}`}>{j.matricula.slice(0,2)}</span><div><strong>{j.matricula}</strong><small>{nombre(j.matricula)}</small><blockquote>“{j.pista}”</blockquote></div>{j.matricula===matricula?<em>Tú</em>:<i>○</i>}</button>)}</div>{!sala.miVoto?<div className="infiltrado-acciones-voto"><button className="infiltrado-pasar" type="button" disabled={cargando} onClick={()=>setVoto("PASAR")}>Pasar · No votar</button><button className="infiltrado-confirmar" type="button" disabled={!voto||cargando} onClick={()=>ejecutar({accion:"votar",codigo:sala.codigo,voto},voto==="PASAR"?"Has decidido pasar.":"Voto registrado.")}>{voto==="PASAR"?"Confirmar que paso":`Confirmar voto a ${voto||"…"}`}</button></div>:<p className="infiltrado-enviado">✓ {sala.miVoto==="PASAR"?"Has pasado sin votar.":"Voto registrado."} Esperando al resto…</p>}</div>}
    {sala.estado==="finalizada"&&<div className="infiltrado-resultado"><span>{sala.acusado===sala.infiltrado?"✓":"!"}</span><h3>El infiltrado era <b>{sala.infiltrado}</b></h3><p>{sala.acusado===sala.infiltrado?"¡El grupo lo descubrió!":sala.empate?"Hubo empate: nadie fue declarado culpable.":sala.acusado?`El grupo acusó a ${sala.acusado}, pero era inocente.`:"Nadie recibió votos suficientes para ser acusado."}</p><small>Temática: {sala.tematica} · {sala.pases} {sala.pases===1?"jugador pasó":"jugadores pasaron"}</small><div>{[...sala.jugadores].sort((a,b)=>(b.votos??0)-(a.votos??0)).map(j=><article key={j.matricula}><strong>{j.matricula}</strong><span><i style={{width:`${(j.votos??0)/sala.jugadores.length*100}%`}}/></span><b>{j.votos??0} votos</b></article>)}</div><div className="infiltrado-resultado-acciones">{sala.soyAnfitrion&&<button type="button" onClick={()=>ejecutar({accion:"repetir",codigo:sala.codigo},"Nueva ronda iniciada con los mismos jugadores.")}>Repetir con el mismo grupo</button>}<button type="button" onClick={salir}>Volver al lobby</button></div></div>}
    <p className="codigo-secreto-mensaje">{mensaje}</p>
  </section>;
};
