import React from "react";
import { CUADRANTES } from "../cuadrante/constantes";

const operadores = Array.from(new Map(CUADRANTES.flatMap(c => c.operadores).map(o => [o.matricula, o])).values()).sort((a,b) => a.matricula.localeCompare(b.matricula));

export const PanelPinesOperadores: React.FC = () => {
  const [matricula, setMatricula] = React.useState(operadores[0]?.matricula ?? ""); const [pin, setPin] = React.useState(""); const [protegidos, setProtegidos] = React.useState<string[]>([]); const [mensaje, setMensaje] = React.useState(""); const [ocupado, setOcupado] = React.useState(false);
  const cargar = React.useCallback(() => fetch("/api/administracion/pines-operadores", { cache:"no-store" }).then(r=>r.json()).then((d:{operadores?:Array<{matricula:string}>})=>setProtegidos((d.operadores??[]).map(o=>o.matricula))).catch(()=>setMensaje("No se pudo cargar la configuración de PIN.")),[]);
  React.useEffect(()=>{cargar();},[cargar]);
  const guardar = async (evento?: React.FormEvent) => { evento?.preventDefault(); if(!/^\d{4,8}$/.test(pin)){setMensaje("Escribe primero un PIN de entre 4 y 8 números.");return;} setOcupado(true);setMensaje(`Protegiendo la matrícula ${matricula}…`);try{const r=await fetch("/api/administracion/pines-operadores",{method:"PUT",credentials:"same-origin",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify({matricula,pin})});const tipo=r.headers.get("content-type")??"";if(!tipo.includes("application/json")){if(r.status===401||r.status===403)throw new Error("La sesión administrativa no es válida.");throw new Error(`El servidor devolvió un error ${r.status}.`);}const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error??`No se pudo guardar el PIN (${r.status}).`);setPin("");setMensaje(`PIN asignado a ${matricula}. Desde ahora sus datos están protegidos.`);await cargar();}catch(error){setMensaje(error instanceof Error?error.message:"No se pudo conectar con el servidor.");}finally{setOcupado(false);} };
  const quitar = async () => { if(!confirm(`¿Retirar temporalmente la protección de ${matricula}?`))return; setOcupado(true); const r=await fetch("/api/administracion/pines-operadores",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({matricula})}); setOcupado(false); if(!r.ok){setMensaje("No se pudo retirar la protección.");return;}setMensaje(`Protección retirada de ${matricula}.`);cargar(); };
  const protegido=protegidos.includes(matricula);
  return <section className="panel-pines-operadores"><header><span>SEGURIDAD · SOLO ADMINISTRADOR</span><h2>PIN personal de Productividad</h2><p>La protección se activa individualmente al asignar un PIN. El PIN nunca se almacena de forma legible.</p></header><form className="panel-pines-formulario" onSubmit={guardar}><label>Operador<select value={matricula} disabled={ocupado} onChange={e=>{setMatricula(e.target.value);setPin("");setMensaje("");}}>{operadores.map(o=><option key={o.matricula} value={o.matricula}>{o.matricula} · {o.nombre}</option>)}</select></label><label>Nuevo PIN<input value={pin} disabled={ocupado} onInput={e=>setPin((e.currentTarget.value||"").replace(/\D/g,"").slice(0,8))} inputMode="numeric" pattern="[0-9]*" type="password" placeholder="4 a 8 números" autoComplete="new-password"/><small>{pin.length ? `${pin.length} cifra${pin.length===1?"":"s"} introducida${pin.length===1?"":"s"}` : "Introduce solamente números"}</small></label><div><button type="submit" disabled={ocupado}>{ocupado?"Protegiendo…":protegido?"Cambiar PIN":"Asignar y proteger"}</button>{protegido&&<button className="quitar" type="button" disabled={ocupado} onClick={quitar}>Retirar protección</button>}</div></form><div className="panel-pines-estado"><strong>{protegido?`🔒 ${matricula} está protegido`:`○ ${matricula} todavía está en transición`}</strong><span>{protegidos.length} matrícula(s) protegida(s)</span></div>{mensaje&&<p role="status" aria-live="polite">{mensaje}</p>}</section>;
};
